apiVersion: apps/v1
kind: Deployment
metadata:
  name: caringup-deployment
  namespace: caringup
  labels:
    app: caringup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caringup
  template:
    metadata:
      labels:
        app: caringup
    spec:
      containers:
        - name: caringup
          image: 547694239239.dkr.ecr.ap-southeast-1.amazonaws.com/caringup_demo:latest
          ports:
            - containerPort: 80
