apiVersion: apps/v1
kind: Deployment
metadata:
  name: caringup-demo
  namespace: demo  # Change if needed
  labels:
    app: caringup-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caringup-demo
  template:
    metadata:
      labels:
        app: caringup-demo
    spec:
      containers:
        - name: caringup-demo-container
          image: 547694239239.dkr.ecr.ap-southeast-1.amazonaws.com/caringup_demo:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
