apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-website
  template:
    metadata:
      labels:
        app: custom-website
    spec:
      containers:
      - name: custom-website-container
        image: 547694239239.dkr.ecr.ap-southeast-1.amazonaws.com/caringup_demo:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
