apiVersion: v1
kind: Service
metadata:
  name: caringup-service
  namespace: caringup
  labels:
    app: caringup
spec:
  selector:
    app: caringup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

