apiVersion: v1
kind: Service
metadata:
  name: custom-website-service
spec:
  selector:
    app: custom-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
