apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: demo-nginx
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 80    # Port on the Pod/container
